import os


TRANSITER_URL = os.getenv("TRANSITER_URL", "http://localhost:8080")

HOUR_NOON = 12
HOUR_5PM = HOUR_NOON + 5
HOUR_8PM = HOUR_NOON + 8

NYC_TIME_ZONE = "America/New_York"


ALLOWED_NUM_STOPS_TO_FINISH = [10, 15, 20, 25]

MAX_MINUTES_SINCE_FIRST_STOP = 15

MIN_NUM_STOPS = ALLOWED_NUM_STOPS_TO_FINISH[0] + 1
